### ISSUE TITLE
Compute the Sketch representing the intersection

### ISSUE THREAD

**Issue by lukaslueg** [axiomhq/hyperminhash#1]
There is `Merge` to compute the `Sketch` representing the union set; yet one can only use `Intersection` to compute a count, not another `Sketch`.

Is it possible to compute a `Sketch` representing the intersecting set?

**Comment by yunwilliamyu** [comment]
Unfortunately, as with the standard MinHash sketch, there is no way to get another Sketch representing the intersecting set. This is because for each bucket, only the minimum number is stored for each set A and B. When you take a union, you simply take the minimum of the two. However, in order to get the sketch for the intersection, you would have to figure out the minimum number that is present in both sets, which is often impossible from the information that is stored.

If you are interested in multi-way intersections of sets A, B, and C though, you can get a count for that too, but still not a sketch.

Apologies.

**Comment by lukaslueg** [comment]
Yes, I'd need a count to the tune of `A ∩ B ∩ C ∪ D ∩ E`. Thanks for the information, closed then.

**Comment by yunwilliamyu** [comment]
When I have that issue, I first form the sketch of $C \cup D$, and then take the intersection count of that with A, B, and E. So long as you rewrite the clause in conjunctive normal form, you can get arbitrary counts, though the error will vary depending on exactly the clause of course.

**Comment by crodwell** [comment]
@yunwilliamyu re your comment `If you are interested in multi-way intersections of sets A, B, and C though, you can get a count for that too, but still not a sketch.` 

I'm really interested in doing this, but can't see any way of achieving it with this package.

Ie, want  `A ∩ B ∩ C ∩ D ∩ E` , but this package only ever allows `A ∩ B`

**Comment by yunwilliamyu** [comment]
This package doesn’t support that function, I think.

Mathematically, it’s not difficult; all you have to do is check all-ways equality of the buckets, and multiply that fraction by the all-ways union cardinality.

I don’t maintain this Go package (which the Axiom folks maintain), but I’m happy to write some code over on my Python package ( https://github.com/yunwilliamyu/hyperminhash ) as a feature request. Porting it over to this Go package would be up to these maintainers (my Go is incredibly rusty, I’m afraid).
